# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

stages:
  - stage: Build
    # pool:
    #   vmImage: ubuntu-latest

    jobs:
      - job: Build
        displayName: "ng devops Build"
        workspace:
          clean: all
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "16.x"
            displayName: "Install Node.js"

          - task: Npm@1
            inputs:
              command: "install"
            displayName: "NPM Install"
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run tsc"
            displayName: "TSC"
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run build"
            displayName: "ng build"