# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    
    jobs:
      - job: Build
        displayName: "ng devops Build"
        workspace:
          clean: all
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "20.x"
            displayName: "Install Node.js"

          - task: Npm@1
            inputs:
              command: "install"
            displayName: "Node Install"
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run tsc"
            displayName: "Type Check"
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run build"
            displayName: "Angular Build"

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true
    
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            
              
  - stage: Deploy
    dependsOn: Build
    jobs:
 
      - job: Deploy
        displayName: "Angular App Deploy"
        steps:
         
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "drop"
              downloadPath: "$(Build.ArtifactStagingDirectory)"
            displayName: "Download Artifact"
             
          

          # - task: AzureRmWebAppDeployment@4
          #   inputs:
          #     ConnectionType: "AzureRM"
          #     azureSubscription: "<Azure Subscription>"
          #     appType: "webAppLinux"
          #     WebAppName: "<Web App Name>"
          #     packageForLinux: "$(Build.ArtifactStagingDirectory)/drop"
          #   displayName: "Deploy to Azure App Service"