# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    
    jobs:
      - job: Build
        displayName: "ng devops Build"
        workspace:
          clean: all
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "18.x"
            displayName: "Install Node.js"

          - task: Npm@1
            inputs:
              command: "install"
            displayName: "Node Install"
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run tsc"
            displayName: "Type Check"
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: "run build"
            displayName: "Angular Build"

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true
    
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            
              
  - stage: Development
    displayName: 'Deploy to Development'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeploymentDevelopment
        pool:
          vmImage: 'ubuntu-latest'
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:

              - task: AzureWebApp@1
                displayName: 'Deploy App Service'
                inputs:
                  azureSubscription: 'b37b48a6-cd9c-4233-91a7-0d64561b3b8a'
                  appType: 'webAppLinux'
                  appName: 'azure-test-pipeline-angular'
                  package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                  runtimeStack: 'NODE|16-lts'